import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionContextProvider from "@/context/SessionContextProvider";
import { CitiesContextProvider } from "@/context/CitiesContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <SessionContextProvider>
          <CitiesContextProvider>{children}</CitiesContextProvider>
        </SessionContextProvider>
      </body>
    </html>
  );
}
